FROM public.ecr.aws/clique/clique-sibyl-dcsv2-base:2.0.1 AS BUILDER
COPY . $APP_DIR/SibylDataConnectors
RUN bash -c "$BUILD_SCRIPT"
RUN rm -rf $APP_DIR/SibylDataConnectors


FROM public.ecr.aws/clique/clique-sibyl-dcsv2-base:2.0.1
COPY --from=BUILDER $APP_DIR $APP_DIR