FROM public.ecr.aws/clique/clique-sibyl-base:2.1.0 AS BUILDER
COPY . $APP_DIR/SibylDataConnectors
RUN bash -c "$BUILD_SCRIPT"
RUN rm -rf $APP_DIR/SibylDataConnectors


FROM public.ecr.aws/clique/clique-sibyl-base:2.1.0
COPY --from=BUILDER $APP_DIR $APP_DIR