FROM public.ecr.aws/clique/clique-sibyl-dcsv2-mtls-service:1.0.0 AS BUILDER
COPY . /sgx/samplecode/SibylDataConnectors
RUN bash -c "$BUILD"
RUN rm -rf /sgx/samplecode/SibylDataConnectors


FROM public.ecr.aws/clique/clique-sibyl-dcsv2-mtls-service:1.0.0
COPY --from=BUILDER /sgx /sgx